"""empty message

Revision ID: 063074671e77
Revises: adbabd9fa0fe
Create Date: 2026-02-03 20:14:09.180428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063074671e77'
down_revision = 'adbabd9fa0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
