"""empty message

Revision ID: 51920af050c8
Revises: 71da12887eec
Create Date: 2026-01-31 15:46:08.235509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51920af050c8'
down_revision = '71da12887eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.drop_column('puede_invitar_proyectos')
        batch_op.drop_column('puede_compartir_reunion')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rol_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('horario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('horario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rol_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puede_compartir_reunion', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('puede_invitar_proyectos', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
