"""empty message

Revision ID: 57e7990ab67e
Revises: d5e2c07a4688
Create Date: 2026-01-09 20:28:32.643789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e7990ab67e'
down_revision = 'd5e2c07a4688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.Column('puede_crear_reunion', sa.Boolean(), nullable=False),
    sa.Column('puede_compartir_reunion', sa.Boolean(), nullable=False),
    sa.Column('puede_invitar_proyectos', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol')
    # ### end Alembic commands ###
