"""empty message

Revision ID: 7607e6593e56
Revises: 
Create Date: 2026-01-12 20:31:54.465123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7607e6593e56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('imaen', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lunes_entrada', sa.Time(), nullable=False),
    sa.Column('lunes_salida', sa.Time(), nullable=False),
    sa.Column('martes_entrada', sa.Time(), nullable=False),
    sa.Column('martes_salida', sa.Time(), nullable=False),
    sa.Column('miercoles_entrada', sa.Time(), nullable=False),
    sa.Column('miercoles_salida', sa.Time(), nullable=False),
    sa.Column('jueves_entrada', sa.Time(), nullable=False),
    sa.Column('jueves_salida', sa.Time(), nullable=False),
    sa.Column('viernes_entrada', sa.Time(), nullable=False),
    sa.Column('viernes_salida', sa.Time(), nullable=False),
    sa.Column('sabado_entrada', sa.Time(), nullable=True),
    sa.Column('sabado_salida', sa.Time(), nullable=True),
    sa.Column('domingo_entrada', sa.Time(), nullable=True),
    sa.Column('domingo_salida', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.Column('puede_crear_reunion', sa.Boolean(), nullable=False),
    sa.Column('puede_compartir_reunion', sa.Boolean(), nullable=False),
    sa.Column('puede_invitar_proyectos', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('apellidos', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('dni', sa.String(length=9), nullable=False),
    sa.Column('foto_perfil', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'ausente', 'ocupado', 'no_molestar', name='estadouser'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('rol')
    op.drop_table('horario')
    op.drop_table('empresa')
    # ### end Alembic commands ###
