"""empty message

Revision ID: bbea3c97f592
Revises: 51920af050c8
Create Date: 2026-02-02 18:36:11.566951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbea3c97f592'
down_revision = '51920af050c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('estado')
        batch_op.drop_column('link_calendly')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_calendly', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estado', postgresql.ENUM('activo', 'ausente', 'ocupado', 'no_molestar', name='estadouser'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('foto_perfil', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
