"""empty message

Revision ID: d5e2c07a4688
Revises: 0763d677d453
Create Date: 2026-01-09 20:09:35.846377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e2c07a4688'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('dni', sa.String(length=9), nullable=False))
        batch_op.add_column(sa.Column('foto_perfil', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['dni'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('dni')
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
